objects = aver.o cpu_intel.o input.o forces.o main.o mdstep.o \
       restart.o scalar.o service.o setup.o tcf.o util.o 

   FC = ifc
   FFLAGS = -O3 -w 
   TARGET = md

default: $(objects) 
	$(FC) -o $(TARGET) $(objects)
   $(objects) : prcm.h dimpar.h

clean: 
	rm -f $(TARGET) *.o
