default:
	make -f Makefile.unknown

risc:
	make -f Makefile.risc	

linux:	
	make -f Makefile.linux  
pgi:	
	make -f Makefile.pgi  
intel:	
	make -f Makefile.ifort
sp2:
	make -f Makefile.sp2
mpi:
	make -f Makefile.mpi
t3e:
	make -f Makefile.T3E_mpi
DEC:
	make -f Makefile.DEC
clean:
	rm -f  *.o
