objects = aver.o cpu_pgi.o input.o forces.o main.o mdstep.o \
       restart.o scalar.o service.o setup.o tcf.o util.o 

   FC = pgf77
   FFLAGS = -O3 -tp p6
   TARGET = md

default: $(objects) 
	$(FC) -o $(TARGET) $(objects)
   $(objects) : prcm.h dimpar.h

clean: 
	rm -f $(TARGET) *.o
