/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#include "adder2.h"

#define f_add F77_FUNC_(f_add2d, F_ADD2D)
#define FORTRAN_ARGS FORTRAN_ARGS2
#define FortranRegion FortranRegion2

extern "C" {
    void f_add(double *, FORTRAN_ARGS, const double *const, FORTRAN_ARGS,
	       FORTRAN_ARGS);
}


/*
void adder2::unpack(s_grid2& G, const Region2& R, double *buf)

add buf to s_grid g when called
*/
void adder2::unpack(s_grid2& G, const Region2& R, double *buf)
{
   FortranRegion g_extents(G.region());
   FortranRegion b_extents(R);
   f_add(FORTRAN_DATA(G), FORTRAN_REGION2(g_extents),
	 buf, FORTRAN_REGION2(b_extents), FORTRAN_REGION2(b_extents));
}


/*
void adder2::copy(const s_grid2& S, const Region2& F, s_grid2& D, const Region2& T)

add s_grid D to s_grid S when called
*/
void adder2::copy(const s_grid2& S, const Region2& F, s_grid2& D, const Region2& T)
{
   FortranRegion s_extents(S.region());
   FortranRegion d_extents(D.region());
   FortranRegion t_extents(T);

   f_add(FORTRAN_DATA(D), FORTRAN_REGION2(d_extents),
	 FORTRAN_DATA(S), FORTRAN_REGION2(s_extents),
         FORTRAN_REGION2(t_extents));
}
