/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#ifndef _adder2_h
#define _adder2_h

/*

The subtractor class is an extension of the mover class, replacing copying
with subtraction

*/

#include "config.h"
#include "kelp.h"
#include "s_grid2.h"
#include "VectorMover2.h"

class adder2: public VectorMover2<s_grid2,double>
{
   void unpack(s_grid2& G, const Region2& R, double *buf);
   void copy(const s_grid2& S, const Region2& F, s_grid2& D, 
	     const Region2& T);
public:
   adder2(XArray2<s_grid2>& send, 
	     XArray2<s_grid2>& recv, MotionPlan2& S): 
      VectorMover2<s_grid2,double>(send, recv, S) {}
};

#endif
