#!/bin/sh

for CURRENT_DIM in 2 3; do
    NEW_FILE=`echo $1 | sed -e "s/\./$CURRENT_DIM\./g"`
    rm -f $NEW_FILE
    echo "/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */

" | cat > $NEW_FILE
    sed -e "s/NDIM/$CURRENT_DIM/g" $1 >> $NEW_FILE
done