/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#include "def.h"

#include "p_grid3.h"

int p_grid3::debug_counter = 0;

