/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#ifndef _io3_h
#define _io3_h

/*

Useful general-purpose i/o operators go here

*/

#include <iostream>
#include <fstream>
#include "kelp.h"
#include "Grid3.h"

#undef OUTPUT
#define OUTPUT(X) { if (mpLeader()) cout << X << flush; }

ostream& operator << (ostream& o, const Grid3<double> &G);

#endif
