/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#include "p_domain3.h"

p_domain3* grow(const p_domain3* b, int dim) {
    p_domain3 *tmp = new p_domain3(*b);
    for_1(i, *b) 
	tmp->grow(i, dim);
//	tmp(i).Region3::grow(dim);
    end_for;
    return tmp;
}

p_domain3 grow(const p_domain3& b, int dim) {
    p_domain3 tmp = p_domain3(b);
    for_1(i, b) 
	tmp.grow(i, dim);
//	tmp(i).Region3::grow(dim);
    end_for;
    return p_domain3(tmp);
}
