/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#include "p_domain2.h"

p_domain2* grow(const p_domain2* b, int dim) {
    p_domain2 *tmp = new p_domain2(*b);
    for_1(i, *b) 
	tmp->grow(i, dim);
//	tmp(i).Region2::grow(dim);
    end_for;
    return tmp;
}

p_domain2 grow(const p_domain2& b, int dim) {
    p_domain2 tmp = p_domain2(b);
    for_1(i, b) 
	tmp.grow(i, dim);
//	tmp(i).Region2::grow(dim);
    end_for;
    return p_domain2(tmp);
}
