/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#ifndef _p_domain3_h
#define _p_domain3_h

/*

This is just a floorplan with a couple extra useful constructs for things I
do a lot.

*/

#include "kelp.h"
#include "dock.h"
#include "Grid3.h"
#include "XArray3.h"
#include "FloorPlan3.h"

class p_domain3: public FloorPlan3
{
 public:
    p_domain3() {}
    p_domain3(const int n) : FloorPlan3(n) {}
    p_domain3(const FloorPlan3& f) : FloorPlan3(f) {}
    p_domain3(const p_domain3& b) : FloorPlan3(b) {}

    void grow(const int index, const int dim) {
	Point3 p(dim);
	(*this).FloorPlan3::grow(index, p);
    }
    void grow(const int dim) {
	for_1(i, *this) 
	    (*this).grow(i, i);
	end_for;
    }
    void coarsen(const int nref) {
	Point3 lo;
	Point3 hi;
	for_1(i, *this) 
	    lo = (*this)(i).lower();
	    hi = (*this)(i).upper();
	    for (int dim = 0; dim < 3; dim++) {
	      lo(dim) = ( (lo(dim) < 0) ? ( (lo(dim) + 1)/nref - 1 ) 
			  : lo(dim)/nref );
	      hi(dim) = ( (hi(dim) < 0) ? ( (hi(0) + 1)/nref - 1 ) 
			  : hi(dim)/nref );
	    }
	    setlower(i, lo);
	    setupper(i, hi);
	end_for;
    }
    void refine(const int nref) {
	Point3 lo;
	Point3 hi;
	for_1(i, *this) 
	    lo = (*this)(i).lower();
	    hi = (*this)(i).upper();
	    lo *= nref;
	    hi = (hi+1)*nref - 1;
	    setlower(i, lo);
	    setupper(i, hi);
	end_for;
    }
    void nrefine(const int nref) {
	Point3 lo;
	Point3 hi;
	for_1(i, *this) 
	    lo = (*this)(i).lower();
	    hi = (*this)(i).upper();
	    lo *= nref;
	    hi *= nref;
	    setlower(i, lo);
	    setupper(i, hi);
	end_for;
    }
    p_domain3& operator=(const p_domain3& b) {
	resize(b.size());
	for_1(i, b) 
	    setowner(i, b(i).owner());
	    setregion(i, b(i));
	end_for;
	return *this;
    }
};

p_domain3 grow(const p_domain3& b, int dim);
p_domain3* grow(const p_domain3* b, int dim);
#endif
