/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#include "p_grid2.h"
#include "adder2.h"
#include "subtractor2.h"
#include "io2.h"


/* the compiler wouldn't accept these in the header file	*/
p_grid2::p_grid2(): fg_plan() {}
p_grid2::~p_grid2() {}


/*
p_grid2::p_grid2(const FloorPlan2& F, const int build_fgp)

construct from a floorplan
*/
p_grid2::p_grid2(const FloorPlan2& F, const int build_fgp)
{
   _ghost = 0;
   instantiate(F, build_fgp);
}


/*
p_grid2::p_grid2(const GhostPlan2& F, const int build_fgp)

construct from a ghostplan
*/
p_grid2::p_grid2(const GhostPlan2& F, const int build_fgp)
{
   instantiate(F,build_fgp);
}


/*
p_grid2::p_grid2(const p_grid2& IG, const int build_fgp)

construct from another p_grid
*/
p_grid2::p_grid2(const p_grid2& IG, const int build_fgp)
{
   instantiate(IG,build_fgp);
}


/*
void p_grid2::instantiate(const FloorPlan2& F,const int build_fgp)

instantiate from a floorplan
*/
void p_grid2::instantiate(const FloorPlan2& F,const int build_fgp)
{
   _ghost = 0;
   debug_counter = 0;
   XArray2<s_grid2>::instantiate(F);
   fill(0.);
   if (build_fgp)
      build_fg_plan();
}


/*
void p_grid2::instantiate(const GhostPlan2& F,const int build_fgp)

instantiate from a ghostplan
*/
void p_grid2::instantiate(const GhostPlan2& F,const int build_fgp)
{
   _ghost = F.ghost();
   debug_counter = 0;
   XArray2<s_grid2>::instantiate(F);
   fill(0.);
   if (build_fgp)
      build_fg_plan();
}


/*
void p_grid2::instantiate(const p_grid2& IG,const int build_fgp)

instantiate from another p_grid
*/
void p_grid2::instantiate(const p_grid2& IG,const int build_fgp)
{
   _ghost = IG.ghost();
   XArray2<s_grid2>::instantiate(IG);
   fill(0.);
   if (build_fgp)
      build_fg_plan();
}


/*
void p_grid2::build_fg_plan()

setup for filling ghost cells
*/
void p_grid2::build_fg_plan()
{
   if (ghost() !=  Point2(0)) {
    for_1(i,*this)
     Region2 inside = interior(i);
     for_1(j,*this)
	if (i != j) {
	  fg_plan.CopyOnIntersection(*this,i,*this,j,inside);
	}
     end_for
    end_for
   }
}


/*
void p_grid2::negate()

negate this whole p_grid
 */
void p_grid2::negate()
{
    for_all(i, *this)
	(*this)(i).negate();
    end_for_all;
}


/*
void p_grid2::fill(const double v)

fill the whole p_grid with v
*/
void p_grid2::fill(const double v)
{
   for_all(i,*this)
      (*this)(i).fill(v);
   end_for_all
}


/*
void p_grid2::assign_ghost(const double v)

fill ghost cells with assigned value v
*/
void p_grid2::assign_ghost(const double v)
{
   for_all(i,*this)
      Region2 R = (*this)(i).region();
      Point2 G = ghost();
      for (GhostIterator2 Boundary(R,G); Boundary; ++Boundary) {
	const Region2 B = Boundary();
	(*this)(i).fill(v,B);
      }
   end_for_all
}


/*
void p_grid2::fillGhost()

fill ghost cells by copying
*/
void p_grid2::fill_ghost()
{
   VectorMover2<s_grid2,double> Ex(*this, *this, fg_plan);
   Ex.execute();
}


/*
void p_grid2::copy_on_intersect(p_grid2 &G)

copy another p_grid on intersection
*/
void p_grid2::copy_on_intersect(p_grid2 &G)
{
   MotionPlan2 S;

   for_1(i,G)
     for_1(j,*this)
       S.CopyOnIntersection(G, i, *this, j);
     end_for
   end_for

   VectorMover2<s_grid2,double> Ex(G,*this,S);
   Ex.execute();
}


/*
void p_grid2::CopyOnIntersection(p_grid2 &G)

copy another p_grid on intersection (an alias for copy_on_intersect)

This method will be removed from the API once I'm sure it is no longer 
necessary (i.e. purged from my main source code).
*/

void p_grid2::CopyOnIntersection(p_grid2 &G)
{
    copy_on_intersect(G);
}


/*
void p_grid2::copy(p_grid2& G)

for each grid in a given p_grid, copy its contents to this p_grid
on intersection
*/
void p_grid2::copy(p_grid2& G)
{
    MotionPlan2 M;
    for_1(i, G) 
	M.CopyOnIntersection(G, i, *this, i);
    end_for;
    VectorMover2<s_grid2,double> Ex(G, *this, M);
    Ex.execute();
}


/*
void p_grid2::copy(p_grid2& G, const FloorPlan2& F)

for each grid in a given p_grid, copy its contents to this p_grid
on the intersection with a given floorplan
*/
void p_grid2::copy(p_grid2& G, const FloorPlan2& F)
{
    MotionPlan2 M;
    for_1(i, G) {
	M.CopyOnIntersection(G, i, *this, i, F(i));
    } end_for;
    VectorMover2<s_grid2,double> Ex(G, *this, M);
    Ex.execute();
}


/*
void p_grid2::copy_grid(p_grid2& from_grid, 
		       int from_index, int to_index)

copy one grid from a given p_grid to a specific grid in this p_grid,
on intersection
*/
void p_grid2::copy_grid(p_grid2& from_grid, 
		       int from_index, int to_index)
{
    MotionPlan2 M;
    M.CopyOnIntersection(from_grid, from_index, *this, to_index);

    VectorMover2<s_grid2,double> Ex(from_grid, *this, M);
    Ex.execute();
}


/*
void p_grid2::add_on_intersect(p_grid2 &G)

add values from a given p_grid to this p_grid on intersection
*/
void p_grid2::add_on_intersect(p_grid2 &G)
{
   MotionPlan2 S;

   for_1(i,G)
     for_1(j,*this)
       S.CopyOnIntersection(G,i,*this,j);
     end_for
   end_for

   adder2 Ex(G,*this,S);
   Ex.execute();
}


/*
void p_grid2::add_grid(p_grid2& from_grid, 
		     int from_index, int to_index)

add values from a single grid in a given p_grid to a specific grid
in this p_grid, on intersection
*/
void p_grid2::add_grid(p_grid2& from_grid, 
		     int from_index, int to_index)
{
    MotionPlan2 M;
    M.CopyOnIntersection(from_grid, from_index, *this, to_index);

    adder2 Ex(from_grid, *this, M);
    Ex.execute();
}


/*
void p_grid2::plus(p_grid2& G)

add values from each grid of a given p_grid to corresponding grids in
this p_grid, on intersection
*/
void p_grid2::plus(p_grid2& G)
{
    MotionPlan2 M;
    for_1(i, G) {
	M.CopyOnIntersection(G, i, *this, i);
    } end_for;
    adder2 Ex(G, *this, M);
    Ex.execute();
}


/*
void p_grid2::plus_all(p_grid2& G)

add on intersection
*/
void p_grid2::plus_all(p_grid2& G)
{
    MotionPlan2 M;
    for_1(i, G) {
	for_1(j, *this) {
	    M.CopyOnIntersection(G, i, *this, j);
	} end_for;
    } end_for;
    adder2 Ex(G, *this, M);
    Ex.execute();
}


/*
void p_grid2::minus(p_grid2& G)

subtract values from each grid of a given p_grid from corresponding grids in
this p_grid, on intersection
*/
void p_grid2::minus(p_grid2& G)
{
    MotionPlan2 M;
    for_1(i, G) {
	M.CopyOnIntersection(G, i, *this, i);
    } end_for;
    subtractor2 Ex(G, *this, M);
    Ex.execute();
}


/*
void p_grid2::mult(double s)

multiply all values in this p_grid by s
*/
void p_grid2::mult(double s)
{
    for_all(i, *this) {
	(*this)(i).mult(s);
    } end_for_all;
}


/* 
double p_grid2::norm(int p)

take the p-norm of this p_grid
*/
double p_grid2::norm(int p)
{
    double result = 0.0;
    double tmpresult = 0.0;

    if (p == 0) {
	for_all(i, *this) {
	    result = MAX((*this)(i).norm(p), result);
	} end_for_all;
	mpReduceMax(&result, 1);
    }
    else if (p == 1) {
	for_all(i, *this) {
	    result += (*this)(i).norm(p);
	} end_for_all;
	mpReduceAdd(&result, 1);
    }
    else if (p == 2) {
	for_all(i, *this) {
	    tmpresult = (*this)(i).norm(p);
	    tmpresult *= tmpresult;
	    result += tmpresult;
	} end_for_all;
	mpReduceAdd(&result, 1);
	result = sqrt(result);
    }

    return result;
}


/*
void p_grid2::debug_print(char *name)

write out the p_grid values for debugging purposes
*/
void p_grid2::debug_print(char *name)
{
    char *file_name = new char[64];
    char *node_name =new char[8];
    ofstream debug_file;
    for (nodeIterator ni(this->floorplan()); ni; ++ni) {
	file_name = strncpy(file_name, name, 55);
	sprintf(node_name, "%03d.%03d", ni()%1000, debug_counter++);
	debug_file.open(strncat(file_name, node_name, 7), ios::out);
	debug_file << operator()(ni());
	debug_file.close();
    }
    delete file_name;
    delete node_name;
}
    
