/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#ifndef _s_grid2_h
#define _s_grid2_h

/*

s_grid is a single processor/serial grid, an extension of the standard
KeLP Grid, with the kinds of extras I use a lot

*/

#include "config.h"
#include "Grid2.h"

#define DIM2D

class f_region2 {
 public:
#if defined(DIM2D)
    int l0, l1, u0, u1;
    f_region2(const Region2& r): l0(r.lower(0)), l1(r.lower(1)),
	u0(r.upper(0)), u1(r.upper(1)) {}
#elif defined(DIM3D)
    int l0, l1, l2, u0, u1, u2;
    f_region3(const Region3& r): l0(r.lower(0)), l1(r.lower(1)),
	l2(r.lower(2)), u0(r.upper(0)), u1(r.upper(1)), u2(r.upper(2)) {}
#else
#error Only 2D and 3D s_grids are defined.
#endif
};    
 
class s_grid2: public Grid2<double> {
 public:
    f_region2 domain;

#if defined(DIM2D)
    s_grid2() : Grid2<double>(), domain(Region2(0, 0, 0, 0)) {}
#elif defined(DIM3D)
    s_grid3() : Grid3<double>(), domain(Region3(0, 0, 0, 0, 0, 0)) {}
#else
#error Only 2D and 3D s_grids are defined.
#endif

    s_grid2(const Region2& region, const int processor) 
	: Grid2<double>(region, processor), domain(region) { 
	cout << region.upper(1) << endl;
    }

    void resize(const Region2& R, const int alloc=TRUE) {
	Grid2<double>::resize(R, alloc);
	domain = f_region2(R);
    }
    void fill(const double val, const Region2& R);
    void fill(const double val) {fill(val,this->region());	}
   void negate();
   void mult(double s);
   double norm(const int p);
};

inline void DefaultPack(s_grid2& G, const Region2& R, double *buf) {  
    G.PackRegion(buf,R);
}

inline void DefaultUnpack(s_grid2& G, const Region2& R, double *buf) {
    G.UnPackRegion(buf,R);
}

inline void DefaultCopy(s_grid2& FG, const Region2& FR, 
			s_grid2& TG, const Region2& TR) {
    TG.CopyRegion(TR,FG,FR);
}

#endif
