/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#include "subtractor2.h"

#define f_subtract F77_FUNC_(f_subtract2d, F_SUBTRACT2D)
#define FORTRAN_ARGS FORTRAN_ARGS2
#define FortranRegion FortranRegion2

extern "C" {
    void f_subtract(double *, FORTRAN_ARGS, const double *const, FORTRAN_ARGS,
		    FORTRAN_ARGS) ;
}


/*
void subtractor2::unpack(s_grid2& G, const Region2& R, double *buf)

subtract buf from s_grid g when called
*/
void subtractor2::unpack(s_grid2& G, const Region2& R, double *buf)
{
   FortranRegion g_extents(G.region());
   FortranRegion b_extents(R);
   f_subtract(FORTRAN_DATA(G), FORTRAN_REGION2(g_extents),
	      buf, FORTRAN_REGION2(b_extents), 
	      FORTRAN_REGION2(b_extents));
}


/*
void subtractor2::copy(const s_grid2& S, const Region2& F, s_grid2& D, 
		      const Region2& T)

subtract s_grid D from s_grid S when called
*/
void subtractor2::copy(const s_grid2& S, const Region2& F, s_grid2& D, 
		      const Region2& T)
{
   FortranRegion s_extents(S.region());
   FortranRegion d_extents(D.region());
   FortranRegion t_extents(T);

   f_subtract(FORTRAN_DATA(D), FORTRAN_REGION2(d_extents),
	      FORTRAN_DATA(S), FORTRAN_REGION2(s_extents),
	      FORTRAN_REGION2(t_extents));
}
