/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#include <stdio.h>

#if defined(__GNUC__)
/* Templates are explicitly instantiated for g++.  
   The other options scare me. */

#include "msg.h"
#include "msg.C"
#include "List.h"
#include "List.C"
#include "Array2.h"
#include "Array2.C"
#include "Grid2.h"
#include "Grid2.C"
#include "XArray2.h"
#include "XArray2.C"
#include "s_grid2.h"
#include "VectorMover2.h"
#include "VectorMover2.C"

template mpMessageID * mpARecv<char>(int, char *, int);
template mpMessageID * mpASend<double>(int, double const *, int, int);
template class KeLP::ListLink<MotionItem2 *>;
template class KeLP::ListIterator<MotionItem2 *>;
template class KeLP::List<MotionItem2 *>;
template class Array2<double>;
template class VectorMover2<s_grid2, double>;
template class XArray2<s_grid2>;
template class Grid2<double>;

#endif // defined(__GNUC__)

#if defined(__xlC__)

#include "s_grid2.h"
#include "XArray2.h"
#include "VectorMover2.h"

#pragma define(XArray2<s_grid2>)
#pragma define(VectorMover2<s_grid2,double>)

#include "XArray2.C"
#include "VectorMover2.C"

#endif // defined(__xlC__)
