/* *** This file is automatically generated by dimensions.sh from a ***
   *** dimension-independent file.  Edit at your peril.             *** */


#include <stdio.h>

#if defined(__GNUC__)
/* Templates are explicitly instantiated for g++.  
   The other options scare me. */

#include "msg.h"
#include "msg.C"
#include "List.h"
#include "List.C"
#include "Array3.h"
#include "Array3.C"
#include "Grid3.h"
#include "Grid3.C"
#include "XArray3.h"
#include "XArray3.C"
#include "s_grid3.h"
#include "VectorMover3.h"
#include "VectorMover3.C"

template mpMessageID * mpARecv<char>(int, char *, int);
template mpMessageID * mpASend<double>(int, double const *, int, int);
template class KeLP::ListLink<MotionItem3 *>;
template class KeLP::ListIterator<MotionItem3 *>;
template class KeLP::List<MotionItem3 *>;
template class Array3<double>;
template class VectorMover3<s_grid3, double>;
template class XArray3<s_grid3>;
template class Grid3<double>;

#endif // defined(__GNUC__)

#if defined(__xlC__)

#include "s_grid3.h"
#include "XArray3.h"
#include "VectorMover3.h"

#pragma define(XArray3<s_grid3>)
#pragma define(VectorMover3<s_grid3,double>)

#include "XArray3.C"
#include "VectorMover3.C"

#endif // defined(__xlC__)
