# Makefile for SGI Origin

SHELL = /bin/sh
.IGNORE:

# System-specific settings

F77 =		f77
F77FLAGS =	-O -DSYNC
CC =		cc
CCFLAGS =	-O -DFFT_SGI
LINK =		f77
LINKFLAGS =	-O
USRLIB =
SYSLIB =	-lmpi -lcomplib.sgimath
SIZE =		size

# Link rule

$(EXE):	$(OBJ)
	$(LINK) $(LINKFLAGS) $(OBJ) $(USRLIB) $(SYSLIB) -o $(EXE)
	$(SIZE) $(EXE)

# Compilation rules

.f.o:
	$(F77) $(F77FLAGS) -c $<

.c.o:
	$(CC) $(CCFLAGS) -c $<

# Individual dependencies

$(OBJ):	$(INC)
