//
// ChemDoodle Web Components uses the following open source software. None
// of these libraries were modified in any way, and are included without
// modification:
//
// - BrowserDetect:   Software URL: http://www.quirksmode.org/js/detect.html
//                    License: Public Domain (no license specified)
// - Explorer Canvas: Software URL: http://code.google.com/p/explorercanvas/
//                    License: Apache License v2.0
//                    License URL: http://www.apache.org/licenses/LICENSE-2.0.html
// - Sylvester:       Software URL: http://sylvester.jcoglan.com/#download
//                    License: MIT License
//                    License URL: http://www.opensource.org/licenses/mit-license.php
// - Trackball:       Ported to javascript by iChemLabs
//                    Software URL: http://scv.bu.edu/documentation/presentations/visualizationworkshop08/materials/opengl/trackball.c
//                    License: MIT License
//                    License URL: http://www.opensource.org/licenses/mit-license.php
// - Queue:           Software URL: http://sylvester.jcoglan.com/#download
//                    License: Public Domain (no license specified)
//
//
// =========================== Browser Detect ===============================

var BrowserDetect={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS";},searchString:function(data){for(var i=0;i<data.length;i++){var dataString=data[i].string;var dataProp=data[i].prop;this.versionSearchString=data[i].versionSearch||data[i].identity;if(dataString){if(dataString.indexOf(data[i].subString)!=-1)
return data[i].identity;}
else
if(dataProp)
return data[i].identity;}},searchVersion:function(dataString){var index=dataString.indexOf(this.versionSearchString);if(index==-1)
return;return parseFloat(dataString.substring(index+this.versionSearchString.length+1));},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};BrowserDetect.init();function alertBrowserIncompatibility(){var good=false;if(BrowserDetect.browser=='Safari'&&BrowserDetect.version>='4'||BrowserDetect.browser=='Firefox'&&BrowserDetect.version>='3.5'||BrowserDetect.browser=='Chrome'){good=true;}
if(!good){alert('ChemDoodle Web Components are best viewed in the following browsers with minimum versions listed. Please use one of the following or update your browser for the best experience.\n\nGoogle Chrome (Windows)\nApple Safari 4+ (Windows, Mac)\nMozilla Firefox 3.5+ (Windows, Mac, Linux)');}}

//
// =========================== Explorer Canvas ===============================
//
// Copyright 2006 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
document.createElement("canvas").getContext||(function(){var s=Math,j=s.round,F=s.sin,G=s.cos,V=s.abs,W=s.sqrt,k=10,v=k/2;function X(){return this.context_||(this.context_=new H(this))}var L=Array.prototype.slice;function Y(b,a){var c=L.call(arguments,2);return function(){return b.apply(a,c.concat(L.call(arguments)))}}var M={init:function(b){if(/MSIE/.test(navigator.userAgent)&&!window.opera){var a=b||document;a.createElement("canvas");a.attachEvent("onreadystatechange",Y(this.init_,this,a))}},init_:function(b){b.namespaces.g_vml_||
b.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML");b.namespaces.g_o_||b.namespaces.add("g_o_","urn:schemas-microsoft-com:office:office","#default#VML");if(!b.styleSheets.ex_canvas_){var a=b.createStyleSheet();a.owningElement.id="ex_canvas_";a.cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}g_vml_\\:*{behavior:url(#default#VML)}g_o_\\:*{behavior:url(#default#VML)}"}var c=b.getElementsByTagName("canvas"),d=0;for(;d<c.length;d++)this.initElement(c[d])},
initElement:function(b){if(!b.getContext){b.getContext=X;b.innerHTML="";b.attachEvent("onpropertychange",Z);b.attachEvent("onresize",$);var a=b.attributes;if(a.width&&a.width.specified)b.style.width=a.width.nodeValue+"px";else b.width=b.clientWidth;if(a.height&&a.height.specified)b.style.height=a.height.nodeValue+"px";else b.height=b.clientHeight}return b}};function Z(b){var a=b.srcElement;switch(b.propertyName){case "width":a.style.width=a.attributes.width.nodeValue+"px";a.getContext().clearRect();
break;case "height":a.style.height=a.attributes.height.nodeValue+"px";a.getContext().clearRect();break}}function $(b){var a=b.srcElement;if(a.firstChild){a.firstChild.style.width=a.clientWidth+"px";a.firstChild.style.height=a.clientHeight+"px"}}M.init();var N=[],B=0;for(;B<16;B++){var C=0;for(;C<16;C++)N[B*16+C]=B.toString(16)+C.toString(16)}function I(){return[[1,0,0],[0,1,0],[0,0,1]]}function y(b,a){var c=I(),d=0;for(;d<3;d++){var f=0;for(;f<3;f++){var h=0,g=0;for(;g<3;g++)h+=b[d][g]*a[g][f];c[d][f]=
h}}return c}function O(b,a){a.fillStyle=b.fillStyle;a.lineCap=b.lineCap;a.lineJoin=b.lineJoin;a.lineWidth=b.lineWidth;a.miterLimit=b.miterLimit;a.shadowBlur=b.shadowBlur;a.shadowColor=b.shadowColor;a.shadowOffsetX=b.shadowOffsetX;a.shadowOffsetY=b.shadowOffsetY;a.strokeStyle=b.strokeStyle;a.globalAlpha=b.globalAlpha;a.arcScaleX_=b.arcScaleX_;a.arcScaleY_=b.arcScaleY_;a.lineScale_=b.lineScale_}function P(b){var a,c=1;b=String(b);if(b.substring(0,3)=="rgb"){var d=b.indexOf("(",3),f=b.indexOf(")",d+
1),h=b.substring(d+1,f).split(",");a="#";var g=0;for(;g<3;g++)a+=N[Number(h[g])];if(h.length==4&&b.substr(3,1)=="a")c=h[3]}else a=b;return{color:a,alpha:c}}function aa(b){switch(b){case "butt":return"flat";case "round":return"round";case "square":default:return"square"}}function H(b){this.m_=I();this.mStack_=[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=k*1;this.globalAlpha=1;this.canvas=b;
var a=b.ownerDocument.createElement("div");a.style.width=b.clientWidth+"px";a.style.height=b.clientHeight+"px";a.style.overflow="hidden";a.style.position="absolute";b.appendChild(a);this.element_=a;this.lineScale_=this.arcScaleY_=this.arcScaleX_=1}var i=H.prototype;i.clearRect=function(){this.element_.innerHTML=""};i.beginPath=function(){this.currentPath_=[]};i.moveTo=function(b,a){var c=this.getCoords_(b,a);this.currentPath_.push({type:"moveTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};
i.lineTo=function(b,a){var c=this.getCoords_(b,a);this.currentPath_.push({type:"lineTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};i.bezierCurveTo=function(b,a,c,d,f,h){var g=this.getCoords_(f,h),l=this.getCoords_(b,a),e=this.getCoords_(c,d);Q(this,l,e,g)};function Q(b,a,c,d){b.currentPath_.push({type:"bezierCurveTo",cp1x:a.x,cp1y:a.y,cp2x:c.x,cp2y:c.y,x:d.x,y:d.y});b.currentX_=d.x;b.currentY_=d.y}i.quadraticCurveTo=function(b,a,c,d){var f=this.getCoords_(b,a),h=this.getCoords_(c,d),g={x:this.currentX_+
0.6666666666666666*(f.x-this.currentX_),y:this.currentY_+0.6666666666666666*(f.y-this.currentY_)};Q(this,g,{x:g.x+(h.x-this.currentX_)/3,y:g.y+(h.y-this.currentY_)/3},h)};i.arc=function(b,a,c,d,f,h){c*=k;var g=h?"at":"wa",l=b+G(d)*c-v,e=a+F(d)*c-v,m=b+G(f)*c-v,r=a+F(f)*c-v;if(l==m&&!h)l+=0.125;var n=this.getCoords_(b,a),o=this.getCoords_(l,e),q=this.getCoords_(m,r);this.currentPath_.push({type:g,x:n.x,y:n.y,radius:c,xStart:o.x,yStart:o.y,xEnd:q.x,yEnd:q.y})};i.rect=function(b,a,c,d){this.moveTo(b,
a);this.lineTo(b+c,a);this.lineTo(b+c,a+d);this.lineTo(b,a+d);this.closePath()};i.strokeRect=function(b,a,c,d){var f=this.currentPath_;this.beginPath();this.moveTo(b,a);this.lineTo(b+c,a);this.lineTo(b+c,a+d);this.lineTo(b,a+d);this.closePath();this.stroke();this.currentPath_=f};i.fillRect=function(b,a,c,d){var f=this.currentPath_;this.beginPath();this.moveTo(b,a);this.lineTo(b+c,a);this.lineTo(b+c,a+d);this.lineTo(b,a+d);this.closePath();this.fill();this.currentPath_=f};i.createLinearGradient=function(b,
a,c,d){var f=new D("gradient");f.x0_=b;f.y0_=a;f.x1_=c;f.y1_=d;return f};i.createRadialGradient=function(b,a,c,d,f,h){var g=new D("gradientradial");g.x0_=b;g.y0_=a;g.r0_=c;g.x1_=d;g.y1_=f;g.r1_=h;return g};i.drawImage=function(b){var a,c,d,f,h,g,l,e,m=b.runtimeStyle.width,r=b.runtimeStyle.height;b.runtimeStyle.width="auto";b.runtimeStyle.height="auto";var n=b.width,o=b.height;b.runtimeStyle.width=m;b.runtimeStyle.height=r;if(arguments.length==3){a=arguments[1];c=arguments[2];h=g=0;l=d=n;e=f=o}else if(arguments.length==
5){a=arguments[1];c=arguments[2];d=arguments[3];f=arguments[4];h=g=0;l=n;e=o}else if(arguments.length==9){h=arguments[1];g=arguments[2];l=arguments[3];e=arguments[4];a=arguments[5];c=arguments[6];d=arguments[7];f=arguments[8]}else throw Error("Invalid number of arguments");var q=this.getCoords_(a,c),t=[];t.push(" <g_vml_:group",' coordsize="',k*10,",",k*10,'"',' coordorigin="0,0"',' style="width:',10,"px;height:",10,"px;position:absolute;");if(this.m_[0][0]!=1||this.m_[0][1]){var E=[];E.push("M11=",
this.m_[0][0],",","M12=",this.m_[1][0],",","M21=",this.m_[0][1],",","M22=",this.m_[1][1],",","Dx=",j(q.x/k),",","Dy=",j(q.y/k),"");var p=q,z=this.getCoords_(a+d,c),w=this.getCoords_(a,c+f),x=this.getCoords_(a+d,c+f);p.x=s.max(p.x,z.x,w.x,x.x);p.y=s.max(p.y,z.y,w.y,x.y);t.push("padding:0 ",j(p.x/k),"px ",j(p.y/k),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",E.join(""),", sizingmethod='clip');")}else t.push("top:",j(q.y/k),"px;left:",j(q.x/k),"px;");t.push(' ">','<g_vml_:image src="',b.src,
'"',' style="width:',k*d,"px;"," height:",k*f,'px;"',' cropleft="',h/n,'"',' croptop="',g/o,'"',' cropright="',(n-h-l)/n,'"',' cropbottom="',(o-g-e)/o,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",t.join(""))};i.stroke=function(b){var a=[],c=P(b?this.fillStyle:this.strokeStyle),d=c.color,f=c.alpha*this.globalAlpha;a.push("<g_vml_:shape",' filled="',!!b,'"',' style="position:absolute;width:',10,"px;height:",10,'px;"',' coordorigin="0 0" coordsize="',k*10," ",k*10,'"',' stroked="',
!b,'"',' path="');var h={x:null,y:null},g={x:null,y:null},l=0;for(;l<this.currentPath_.length;l++){var e=this.currentPath_[l];switch(e.type){case "moveTo":a.push(" m ",j(e.x),",",j(e.y));break;case "lineTo":a.push(" l ",j(e.x),",",j(e.y));break;case "close":a.push(" x ");e=null;break;case "bezierCurveTo":a.push(" c ",j(e.cp1x),",",j(e.cp1y),",",j(e.cp2x),",",j(e.cp2y),",",j(e.x),",",j(e.y));break;case "at":case "wa":a.push(" ",e.type," ",j(e.x-this.arcScaleX_*e.radius),",",j(e.y-this.arcScaleY_*e.radius),
" ",j(e.x+this.arcScaleX_*e.radius),",",j(e.y+this.arcScaleY_*e.radius)," ",j(e.xStart),",",j(e.yStart)," ",j(e.xEnd),",",j(e.yEnd));break}if(e){if(h.x==null||e.x<h.x)h.x=e.x;if(g.x==null||e.x>g.x)g.x=e.x;if(h.y==null||e.y<h.y)h.y=e.y;if(g.y==null||e.y>g.y)g.y=e.y}}a.push(' ">');if(b)if(typeof this.fillStyle=="object"){var m=this.fillStyle,r=0,n={x:0,y:0},o=0,q=1;if(m.type_=="gradient"){var t=m.x1_/this.arcScaleX_,E=m.y1_/this.arcScaleY_,p=this.getCoords_(m.x0_/this.arcScaleX_,m.y0_/this.arcScaleY_),
z=this.getCoords_(t,E);r=Math.atan2(z.x-p.x,z.y-p.y)*180/Math.PI;if(r<0)r+=360;if(r<1.0E-6)r=0}else{var p=this.getCoords_(m.x0_,m.y0_),w=g.x-h.x,x=g.y-h.y;n={x:(p.x-h.x)/w,y:(p.y-h.y)/x};w/=this.arcScaleX_*k;x/=this.arcScaleY_*k;var R=s.max(w,x);o=2*m.r0_/R;q=2*m.r1_/R-o}var u=m.colors_;u.sort(function(ba,ca){return ba.offset-ca.offset});var J=u.length,da=u[0].color,ea=u[J-1].color,fa=u[0].alpha*this.globalAlpha,ga=u[J-1].alpha*this.globalAlpha,S=[],l=0;for(;l<J;l++){var T=u[l];S.push(T.offset*q+
o+" "+T.color)}a.push('<g_vml_:fill type="',m.type_,'"',' method="none" focus="100%"',' color="',da,'"',' color2="',ea,'"',' colors="',S.join(","),'"',' opacity="',ga,'"',' g_o_:opacity2="',fa,'"',' angle="',r,'"',' focusposition="',n.x,",",n.y,'" />')}else a.push('<g_vml_:fill color="',d,'" opacity="',f,'" />');else{var K=this.lineScale_*this.lineWidth;if(K<1)f*=K;a.push("<g_vml_:stroke",' opacity="',f,'"',' joinstyle="',this.lineJoin,'"',' miterlimit="',this.miterLimit,'"',' endcap="',aa(this.lineCap),
'"',' weight="',K,'px"',' color="',d,'" />')}a.push("</g_vml_:shape>");this.element_.insertAdjacentHTML("beforeEnd",a.join(""))};i.fill=function(){this.stroke(true)};i.closePath=function(){this.currentPath_.push({type:"close"})};i.getCoords_=function(b,a){var c=this.m_;return{x:k*(b*c[0][0]+a*c[1][0]+c[2][0])-v,y:k*(b*c[0][1]+a*c[1][1]+c[2][1])-v}};i.save=function(){var b={};O(this,b);this.aStack_.push(b);this.mStack_.push(this.m_);this.m_=y(I(),this.m_)};i.restore=function(){O(this.aStack_.pop(),
this);this.m_=this.mStack_.pop()};function ha(b){var a=0;for(;a<3;a++){var c=0;for(;c<2;c++)if(!isFinite(b[a][c])||isNaN(b[a][c]))return false}return true}function A(b,a,c){if(!!ha(a)){b.m_=a;if(c)b.lineScale_=W(V(a[0][0]*a[1][1]-a[0][1]*a[1][0]))}}i.translate=function(b,a){A(this,y([[1,0,0],[0,1,0],[b,a,1]],this.m_),false)};i.rotate=function(b){var a=G(b),c=F(b);A(this,y([[a,c,0],[-c,a,0],[0,0,1]],this.m_),false)};i.scale=function(b,a){this.arcScaleX_*=b;this.arcScaleY_*=a;A(this,y([[b,0,0],[0,a,
0],[0,0,1]],this.m_),true)};i.transform=function(b,a,c,d,f,h){A(this,y([[b,a,0],[c,d,0],[f,h,1]],this.m_),true)};i.setTransform=function(b,a,c,d,f,h){A(this,[[b,a,0],[c,d,0],[f,h,1]],true)};i.clip=function(){};i.arcTo=function(){};i.createPattern=function(){return new U};function D(b){this.type_=b;this.r1_=this.y1_=this.x1_=this.r0_=this.y0_=this.x0_=0;this.colors_=[]}D.prototype.addColorStop=function(b,a){a=P(a);this.colors_.push({offset:b,color:a.color,alpha:a.alpha})};function U(){}G_vmlCanvasManager=
M;CanvasRenderingContext2D=H;CanvasGradient=D;CanvasPattern=U})();
//
// =========================== Sylvester ===============================
//
// Vector and Matrix mathematics modules for JavaScript
// Copyright (c) 2007 James Coglan
// 
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//
var Sylvester={version:'0.1.3',precision:1e-6};function Vector(){}
Vector.prototype={e:function(i){return(i<1||i>this.elements.length)?null:this.elements[i-1];},dimensions:function(){return this.elements.length;},modulus:function(){return Math.sqrt(this.dot(this));},eql:function(vector){var n=this.elements.length;var V=vector.elements||vector;if(n!=V.length){return false;}
do{if(Math.abs(this.elements[n-1]-V[n-1])>Sylvester.precision){return false;}}while(--n);return true;},dup:function(){return Vector.create(this.elements);},map:function(fn){var elements=[];this.each(function(x,i){elements.push(fn(x,i));});return Vector.create(elements);},each:function(fn){var n=this.elements.length,k=n,i;do{i=k-n;fn(this.elements[i],i+1);}while(--n);},toUnitVector:function(){var r=this.modulus();if(r===0){return this.dup();}
return this.map(function(x){return x/r;});},angleFrom:function(vector){var V=vector.elements||vector;var n=this.elements.length,k=n,i;if(n!=V.length){return null;}
var dot=0,mod1=0,mod2=0;this.each(function(x,i){dot+=x*V[i-1];mod1+=x*x;mod2+=V[i-1]*V[i-1];});mod1=Math.sqrt(mod1);mod2=Math.sqrt(mod2);if(mod1*mod2===0){return null;}
var theta=dot/(mod1*mod2);if(theta<-1){theta=-1;}
if(theta>1){theta=1;}
return Math.acos(theta);},isParallelTo:function(vector){var angle=this.angleFrom(vector);return(angle===null)?null:(angle<=Sylvester.precision);},isAntiparallelTo:function(vector){var angle=this.angleFrom(vector);return(angle===null)?null:(Math.abs(angle-Math.PI)<=Sylvester.precision);},isPerpendicularTo:function(vector){var dot=this.dot(vector);return(dot===null)?null:(Math.abs(dot)<=Sylvester.precision);},add:function(vector){var V=vector.elements||vector;if(this.elements.length!=V.length){return null;}
return this.map(function(x,i){return x+V[i-1];});},subtract:function(vector){var V=vector.elements||vector;if(this.elements.length!=V.length){return null;}
return this.map(function(x,i){return x-V[i-1];});},multiply:function(k){return this.map(function(x){return x*k;});},x:function(k){return this.multiply(k);},dot:function(vector){var V=vector.elements||vector;var i,product=0,n=this.elements.length;if(n!=V.length){return null;}
do{product+=this.elements[n-1]*V[n-1];}while(--n);return product;},cross:function(vector){var B=vector.elements||vector;if(this.elements.length!=3||B.length!=3){return null;}
var A=this.elements;return Vector.create([(A[1]*B[2])-(A[2]*B[1]),(A[2]*B[0])-(A[0]*B[2]),(A[0]*B[1])-(A[1]*B[0])]);},max:function(){var m=0,n=this.elements.length,k=n,i;do{i=k-n;if(Math.abs(this.elements[i])>Math.abs(m)){m=this.elements[i];}}while(--n);return m;},indexOf:function(x){var index=null,n=this.elements.length,k=n,i;do{i=k-n;if(index===null&&this.elements[i]==x){index=i+1;}}while(--n);return index;},toDiagonalMatrix:function(){return Matrix.Diagonal(this.elements);},round:function(){return this.map(function(x){return Math.round(x);});},snapTo:function(x){return this.map(function(y){return(Math.abs(y-x)<=Sylvester.precision)?x:y;});},distanceFrom:function(obj){if(obj.anchor){return obj.distanceFrom(this);}
var V=obj.elements||obj;if(V.length!=this.elements.length){return null;}
var sum=0,part;this.each(function(x,i){part=x-V[i-1];sum+=part*part;});return Math.sqrt(sum);},liesOn:function(line){return line.contains(this);},liesIn:function(plane){return plane.contains(this);},rotate:function(t,obj){var V,R,x,y,z;switch(this.elements.length){case 2:V=obj.elements||obj;if(V.length!=2){return null;}
R=Matrix.Rotation(t).elements;x=this.elements[0]-V[0];y=this.elements[1]-V[1];return Vector.create([V[0]+R[0][0]*x+R[0][1]*y,V[1]+R[1][0]*x+R[1][1]*y]);break;case 3:if(!obj.direction){return null;}
var C=obj.pointClosestTo(this).elements;R=Matrix.Rotation(t,obj.direction).elements;x=this.elements[0]-C[0];y=this.elements[1]-C[1];z=this.elements[2]-C[2];return Vector.create([C[0]+R[0][0]*x+R[0][1]*y+R[0][2]*z,C[1]+R[1][0]*x+R[1][1]*y+R[1][2]*z,C[2]+R[2][0]*x+R[2][1]*y+R[2][2]*z]);break;default:return null;}},reflectionIn:function(obj){if(obj.anchor){var P=this.elements.slice();var C=obj.pointClosestTo(P).elements;return Vector.create([C[0]+(C[0]-P[0]),C[1]+(C[1]-P[1]),C[2]+(C[2]-(P[2]||0))]);}else{var Q=obj.elements||obj;if(this.elements.length!=Q.length){return null;}
return this.map(function(x,i){return Q[i-1]+(Q[i-1]-x);});}},to3D:function(){var V=this.dup();switch(V.elements.length){case 3:break;case 2:V.elements.push(0);break;default:return null;}
return V;},inspect:function(){return'['+this.elements.join(', ')+']';},setElements:function(els){this.elements=(els.elements||els).slice();return this;}};Vector.create=function(elements){var V=new Vector();return V.setElements(elements);};Vector.i=Vector.create([1,0,0]);Vector.j=Vector.create([0,1,0]);Vector.k=Vector.create([0,0,1]);Vector.Random=function(n){var elements=[];do{elements.push(Math.random());}while(--n);return Vector.create(elements);};Vector.Zero=function(n){var elements=[];do{elements.push(0);}while(--n);return Vector.create(elements);};function Matrix(){}
Matrix.prototype={e:function(i,j){if(i<1||i>this.elements.length||j<1||j>this.elements[0].length){return null;}
return this.elements[i-1][j-1];},row:function(i){if(i>this.elements.length){return null;}
return Vector.create(this.elements[i-1]);},col:function(j){if(j>this.elements[0].length){return null;}
var col=[],n=this.elements.length,k=n,i;do{i=k-n;col.push(this.elements[i][j-1]);}while(--n);return Vector.create(col);},dimensions:function(){return{rows:this.elements.length,cols:this.elements[0].length};},rows:function(){return this.elements.length;},cols:function(){return this.elements[0].length;},eql:function(matrix){var M=matrix.elements||matrix;if(typeof(M[0][0])=='undefined'){M=Matrix.create(M).elements;}
if(this.elements.length!=M.length||this.elements[0].length!=M[0].length){return false;}
var ni=this.elements.length,ki=ni,i,nj,kj=this.elements[0].length,j;do{i=ki-ni;nj=kj;do{j=kj-nj;if(Math.abs(this.elements[i][j]-M[i][j])>Sylvester.precision){return false;}}while(--nj);}while(--ni);return true;},dup:function(){return Matrix.create(this.elements);},map:function(fn){var els=[],ni=this.elements.length,ki=ni,i,nj,kj=this.elements[0].length,j;do{i=ki-ni;nj=kj;els[i]=[];do{j=kj-nj;els[i][j]=fn(this.elements[i][j],i+1,j+1);}while(--nj);}while(--ni);return Matrix.create(els);},isSameSizeAs:function(matrix){var M=matrix.elements||matrix;if(typeof(M[0][0])=='undefined'){M=Matrix.create(M).elements;}
return(this.elements.length==M.length&&this.elements[0].length==M[0].length);},add:function(matrix){var M=matrix.elements||matrix;if(typeof(M[0][0])=='undefined'){M=Matrix.create(M).elements;}
if(!this.isSameSizeAs(M)){return null;}
return this.map(function(x,i,j){return x+M[i-1][j-1];});},subtract:function(matrix){var M=matrix.elements||matrix;if(typeof(M[0][0])=='undefined'){M=Matrix.create(M).elements;}
if(!this.isSameSizeAs(M)){return null;}
return this.map(function(x,i,j){return x-M[i-1][j-1];});},canMultiplyFromLeft:function(matrix){var M=matrix.elements||matrix;if(typeof(M[0][0])=='undefined'){M=Matrix.create(M).elements;}
return(this.elements[0].length==M.length);},multiply:function(matrix){if(!matrix.elements){return this.map(function(x){return x*matrix;});}
var returnVector=matrix.modulus?true:false;var M=matrix.elements||matrix;if(typeof(M[0][0])=='undefined'){M=Matrix.create(M).elements;}
if(!this.canMultiplyFromLeft(M)){return null;}
var ni=this.elements.length,ki=ni,i,nj,kj=M[0].length,j;var cols=this.elements[0].length,elements=[],sum,nc,c;do{i=ki-ni;elements[i]=[];nj=kj;do{j=kj-nj;sum=0;nc=cols;do{c=cols-nc;sum+=this.elements[i][c]*M[c][j];}while(--nc);elements[i][j]=sum;}while(--nj);}while(--ni);var M=Matrix.create(elements);return returnVector?M.col(1):M;},x:function(matrix){return this.multiply(matrix);},minor:function(a,b,c,d){var elements=[],ni=c,i,nj,j;var rows=this.elements.length,cols=this.elements[0].length;do{i=c-ni;elements[i]=[];nj=d;do{j=d-nj;elements[i][j]=this.elements[(a+i-1)%rows][(b+j-1)%cols];}while(--nj);}while(--ni);return Matrix.create(elements);},transpose:function(){var rows=this.elements.length,cols=this.elements[0].length;var elements=[],ni=cols,i,nj,j;do{i=cols-ni;elements[i]=[];nj=rows;do{j=rows-nj;elements[i][j]=this.elements[j][i];}while(--nj);}while(--ni);return Matrix.create(elements);},isSquare:function(){return(this.elements.length==this.elements[0].length);},max:function(){var m=0,ni=this.elements.length,ki=ni,i,nj,kj=this.elements[0].length,j;do{i=ki-ni;nj=kj;do{j=kj-nj;if(Math.abs(this.elements[i][j])>Math.abs(m)){m=this.elements[i][j];}}while(--nj);}while(--ni);return m;},indexOf:function(x){var index=null,ni=this.elements.length,ki=ni,i,nj,kj=this.elements[0].length,j;do{i=ki-ni;nj=kj;do{j=kj-nj;if(this.elements[i][j]==x){return{i:i+1,j:j+1};}}while(--nj);}while(--ni);return null;},diagonal:function(){if(!this.isSquare){return null;}
var els=[],n=this.elements.length,k=n,i;do{i=k-n;els.push(this.elements[i][i]);}while(--n);return Vector.create(els);},toRightTriangular:function(){var M=this.dup(),els;var n=this.elements.length,k=n,i,np,kp=this.elements[0].length,p;do{i=k-n;if(M.elements[i][i]==0){for(j=i+1;j<k;j++){if(M.elements[j][i]!=0){els=[];np=kp;do{p=kp-np;els.push(M.elements[i][p]+M.elements[j][p]);}while(--np);M.elements[i]=els;break;}}}
if(M.elements[i][i]!=0){for(j=i+1;j<k;j++){var multiplier=M.elements[j][i]/M.elements[i][i];els=[];np=kp;do{p=kp-np;els.push(p<=i?0:M.elements[j][p]-M.elements[i][p]*multiplier);}while(--np);M.elements[j]=els;}}}while(--n);return M;},toUpperTriangular:function(){return this.toRightTriangular();},determinant:function(){if(!this.isSquare()){return null;}
var M=this.toRightTriangular();var det=M.elements[0][0],n=M.elements.length-1,k=n,i;do{i=k-n+1;det=det*M.elements[i][i];}while(--n);return det;},det:function(){return this.determinant();},isSingular:function(){return(this.isSquare()&&this.determinant()===0);},trace:function(){if(!this.isSquare()){return null;}
var tr=this.elements[0][0],n=this.elements.length-1,k=n,i;do{i=k-n+1;tr+=this.elements[i][i];}while(--n);return tr;},tr:function(){return this.trace();},rank:function(){var M=this.toRightTriangular(),rank=0;var ni=this.elements.length,ki=ni,i,nj,kj=this.elements[0].length,j;do{i=ki-ni;nj=kj;do{j=kj-nj;if(Math.abs(M.elements[i][j])>Sylvester.precision){rank++;break;}}while(--nj);}while(--ni);return rank;},rk:function(){return this.rank();},augment:function(matrix){var M=matrix.elements||matrix;if(typeof(M[0][0])=='undefined'){M=Matrix.create(M).elements;}
var T=this.dup(),cols=T.elements[0].length;var ni=T.elements.length,ki=ni,i,nj,kj=M[0].length,j;if(ni!=M.length){return null;}
do{i=ki-ni;nj=kj;do{j=kj-nj;T.elements[i][cols+j]=M[i][j];}while(--nj);}while(--ni);return T;},inverse:function(){if(!this.isSquare()||this.isSingular()){return null;}
var ni=this.elements.length,ki=ni,i,j;var M=this.augment(Matrix.I(ni)).toRightTriangular();var np,kp=M.elements[0].length,p,els,divisor;var inverse_elements=[],new_element;do{i=ni-1;els=[];np=kp;inverse_elements[i]=[];divisor=M.elements[i][i];do{p=kp-np;new_element=M.elements[i][p]/divisor;els.push(new_element);if(p>=ki){inverse_elements[i].push(new_element);}}while(--np);M.elements[i]=els;for(j=0;j<i;j++){els=[];np=kp;do{p=kp-np;els.push(M.elements[j][p]-M.elements[i][p]*M.elements[j][i]);}while(--np);M.elements[j]=els;}}while(--ni);return Matrix.create(inverse_elements);},inv:function(){return this.inverse();},round:function(){return this.map(function(x){return Math.round(x);});},snapTo:function(x){return this.map(function(p){return(Math.abs(p-x)<=Sylvester.precision)?x:p;});},inspect:function(){var matrix_rows=[];var n=this.elements.length,k=n,i;do{i=k-n;matrix_rows.push(Vector.create(this.elements[i]).inspect());}while(--n);return matrix_rows.join('\n');},setElements:function(els){var i,elements=els.elements||els;if(typeof(elements[0][0])!='undefined'){var ni=elements.length,ki=ni,nj,kj,j;this.elements=[];do{i=ki-ni;nj=elements[i].length;kj=nj;this.elements[i]=[];do{j=kj-nj;this.elements[i][j]=elements[i][j];}while(--nj);}while(--ni);return this;}
var n=elements.length,k=n;this.elements=[];do{i=k-n;this.elements.push([elements[i]]);}while(--n);return this;}};Matrix.create=function(elements){var M=new Matrix();return M.setElements(elements);};Matrix.I=function(n){var els=[],k=n,i,nj,j;do{i=k-n;els[i]=[];nj=k;do{j=k-nj;els[i][j]=(i==j)?1:0;}while(--nj);}while(--n);return Matrix.create(els);};Matrix.Diagonal=function(elements){var n=elements.length,k=n,i;var M=Matrix.I(n);do{i=k-n;M.elements[i][i]=elements[i];}while(--n);return M;};Matrix.Rotation=function(theta,a){if(!a){return Matrix.create([[Math.cos(theta),-Math.sin(theta)],[Math.sin(theta),Math.cos(theta)]]);}
var axis=a.dup();if(axis.elements.length!=3){return null;}
var mod=axis.modulus();var x=axis.elements[0]/mod,y=axis.elements[1]/mod,z=axis.elements[2]/mod;var s=Math.sin(theta),c=Math.cos(theta),t=1-c;return Matrix.create([[t*x*x+c,t*x*y-s*z,t*x*z+s*y],[t*x*y+s*z,t*y*y+c,t*y*z-s*x],[t*x*z-s*y,t*y*z+s*x,t*z*z+c]]);};Matrix.RotationX=function(t){var c=Math.cos(t),s=Math.sin(t);return Matrix.create([[1,0,0],[0,c,-s],[0,s,c]]);};Matrix.RotationY=function(t){var c=Math.cos(t),s=Math.sin(t);return Matrix.create([[c,0,s],[0,1,0],[-s,0,c]]);};Matrix.RotationZ=function(t){var c=Math.cos(t),s=Math.sin(t);return Matrix.create([[c,-s,0],[s,c,0],[0,0,1]]);};Matrix.Random=function(n,m){return Matrix.Zero(n,m).map(function(){return Math.random();});};Matrix.Zero=function(n,m){var els=[],ni=n,i,nj,j;do{i=n-ni;els[i]=[];nj=m;do{j=m-nj;els[i][j]=0;}while(--nj);}while(--ni);return Matrix.create(els);};function Line(){}
Line.prototype={eql:function(line){return(this.isParallelTo(line)&&this.contains(line.anchor));},dup:function(){return Line.create(this.anchor,this.direction);},translate:function(vector){var V=vector.elements||vector;return Line.create([this.anchor.elements[0]+V[0],this.anchor.elements[1]+V[1],this.anchor.elements[2]+(V[2]||0)],this.direction);},isParallelTo:function(obj){if(obj.normal){return obj.isParallelTo(this);}
var theta=this.direction.angleFrom(obj.direction);return(Math.abs(theta)<=Sylvester.precision||Math.abs(theta-Math.PI)<=Sylvester.precision);},distanceFrom:function(obj){if(obj.normal){return obj.distanceFrom(this);}
if(obj.direction){if(this.isParallelTo(obj)){return this.distanceFrom(obj.anchor);}
var N=this.direction.cross(obj.direction).toUnitVector().elements;var A=this.anchor.elements,B=obj.anchor.elements;return Math.abs((A[0]-B[0])*N[0]+(A[1]-B[1])*N[1]+(A[2]-B[2])*N[2]);}else{var P=obj.elements||obj;var A=this.anchor.elements,D=this.direction.elements;var PA1=P[0]-A[0],PA2=P[1]-A[1],PA3=(P[2]||0)-A[2];var modPA=Math.sqrt(PA1*PA1+PA2*PA2+PA3*PA3);if(modPA===0)return 0;var cosTheta=(PA1*D[0]+PA2*D[1]+PA3*D[2])/modPA;var sin2=1-cosTheta*cosTheta;return Math.abs(modPA*Math.sqrt(sin2<0?0:sin2));}},contains:function(point){var dist=this.distanceFrom(point);return(dist!==null&&dist<=Sylvester.precision);},liesIn:function(plane){return plane.contains(this);},intersects:function(obj){if(obj.normal){return obj.intersects(this);}
return(!this.isParallelTo(obj)&&this.distanceFrom(obj)<=Sylvester.precision);},intersectionWith:function(obj){if(obj.normal){return obj.intersectionWith(this);}
if(!this.intersects(obj)){return null;}
var P=this.anchor.elements,X=this.direction.elements,Q=obj.anchor.elements,Y=obj.direction.elements;var X1=X[0],X2=X[1],X3=X[2],Y1=Y[0],Y2=Y[1],Y3=Y[2];var PsubQ1=P[0]-Q[0],PsubQ2=P[1]-Q[1],PsubQ3=P[2]-Q[2];var XdotQsubP=-X1*PsubQ1-X2*PsubQ2-X3*PsubQ3;var YdotPsubQ=Y1*PsubQ1+Y2*PsubQ2+Y3*PsubQ3;var XdotX=X1*X1+X2*X2+X3*X3;var YdotY=Y1*Y1+Y2*Y2+Y3*Y3;var XdotY=X1*Y1+X2*Y2+X3*Y3;var k=(XdotQsubP*YdotY/XdotX+XdotY*YdotPsubQ)/(YdotY-XdotY*XdotY);return Vector.create([P[0]+k*X1,P[1]+k*X2,P[2]+k*X3]);},pointClosestTo:function(obj){if(obj.direction){if(this.intersects(obj)){return this.intersectionWith(obj);}
if(this.isParallelTo(obj)){return null;}
var D=this.direction.elements,E=obj.direction.elements;var D1=D[0],D2=D[1],D3=D[2],E1=E[0],E2=E[1],E3=E[2];var x=(D3*E1-D1*E3),y=(D1*E2-D2*E1),z=(D2*E3-D3*E2);var N=Vector.create([x*E3-y*E2,y*E1-z*E3,z*E2-x*E1]);var P=Plane.create(obj.anchor,N);return P.intersectionWith(this);}else{var P=obj.elements||obj;if(this.contains(P)){return Vector.create(P);}
var A=this.anchor.elements,D=this.direction.elements;var D1=D[0],D2=D[1],D3=D[2],A1=A[0],A2=A[1],A3=A[2];var x=D1*(P[1]-A2)-D2*(P[0]-A1),y=D2*((P[2]||0)-A3)-D3*(P[1]-A2),z=D3*(P[0]-A1)-D1*((P[2]||0)-A3);var V=Vector.create([D2*x-D3*z,D3*y-D1*x,D1*z-D2*y]);var k=this.distanceFrom(P)/V.modulus();return Vector.create([P[0]+V.elements[0]*k,P[1]+V.elements[1]*k,(P[2]||0)+V.elements[2]*k]);}},rotate:function(t,line){if(typeof(line.direction)=='undefined'){line=Line.create(line.to3D(),Vector.k);}
var R=Matrix.Rotation(t,line.direction).elements;var C=line.pointClosestTo(this.anchor).elements;var A=this.anchor.elements,D=this.direction.elements;var C1=C[0],C2=C[1],C3=C[2],A1=A[0],A2=A[1],A3=A[2];var x=A1-C1,y=A2-C2,z=A3-C3;return Line.create([C1+R[0][0]*x+R[0][1]*y+R[0][2]*z,C2+R[1][0]*x+R[1][1]*y+R[1][2]*z,C3+R[2][0]*x+R[2][1]*y+R[2][2]*z],[R[0][0]*D[0]+R[0][1]*D[1]+R[0][2]*D[2],R[1][0]*D[0]+R[1][1]*D[1]+R[1][2]*D[2],R[2][0]*D[0]+R[2][1]*D[1]+R[2][2]*D[2]]);},reflectionIn:function(obj){if(obj.normal){var A=this.anchor.elements,D=this.direction.elements;var A1=A[0],A2=A[1],A3=A[2],D1=D[0],D2=D[1],D3=D[2];var newA=this.anchor.reflectionIn(obj).elements;var AD1=A1+D1,AD2=A2+D2,AD3=A3+D3;var Q=obj.pointClosestTo([AD1,AD2,AD3]).elements;var newD=[Q[0]+(Q[0]-AD1)-newA[0],Q[1]+(Q[1]-AD2)-newA[1],Q[2]+(Q[2]-AD3)-newA[2]];return Line.create(newA,newD);}else if(obj.direction){return this.rotate(Math.PI,obj);}else{var P=obj.elements||obj;return Line.create(this.anchor.reflectionIn([P[0],P[1],(P[2]||0)]),this.direction);}},setVectors:function(anchor,direction){anchor=Vector.create(anchor);direction=Vector.create(direction);if(anchor.elements.length==2){anchor.elements.push(0);}
if(direction.elements.length==2){direction.elements.push(0);}
if(anchor.elements.length>3||direction.elements.length>3){return null;}
var mod=direction.modulus();if(mod===0){return null;}
this.anchor=anchor;this.direction=Vector.create([direction.elements[0]/mod,direction.elements[1]/mod,direction.elements[2]/mod]);return this;}};Line.create=function(anchor,direction){var L=new Line();return L.setVectors(anchor,direction);};Line.X=Line.create(Vector.Zero(3),Vector.i);Line.Y=Line.create(Vector.Zero(3),Vector.j);Line.Z=Line.create(Vector.Zero(3),Vector.k);function Plane(){}
Plane.prototype={eql:function(plane){return(this.contains(plane.anchor)&&this.isParallelTo(plane));},dup:function(){return Plane.create(this.anchor,this.normal);},translate:function(vector){var V=vector.elements||vector;return Plane.create([this.anchor.elements[0]+V[0],this.anchor.elements[1]+V[1],this.anchor.elements[2]+(V[2]||0)],this.normal);},isParallelTo:function(obj){var theta;if(obj.normal){theta=this.normal.angleFrom(obj.normal);return(Math.abs(theta)<=Sylvester.precision||Math.abs(Math.PI-theta)<=Sylvester.precision);}else if(obj.direction){return this.normal.isPerpendicularTo(obj.direction);}
return null;},isPerpendicularTo:function(plane){var theta=this.normal.angleFrom(plane.normal);return(Math.abs(Math.PI/2-theta)<=Sylvester.precision);},distanceFrom:function(obj){if(this.intersects(obj)||this.contains(obj)){return 0;}
if(obj.anchor){var A=this.anchor.elements,B=obj.anchor.elements,N=this.normal.elements;return Math.abs((A[0]-B[0])*N[0]+(A[1]-B[1])*N[1]+(A[2]-B[2])*N[2]);}else{var P=obj.elements||obj;var A=this.anchor.elements,N=this.normal.elements;return Math.abs((A[0]-P[0])*N[0]+(A[1]-P[1])*N[1]+(A[2]-(P[2]||0))*N[2]);}},contains:function(obj){if(obj.normal){return null;}
if(obj.direction){return(this.contains(obj.anchor)&&this.contains(obj.anchor.add(obj.direction)));}else{var P=obj.elements||obj;var A=this.anchor.elements,N=this.normal.elements;var diff=Math.abs(N[0]*(A[0]-P[0])+N[1]*(A[1]-P[1])+N[2]*(A[2]-(P[2]||0)));return(diff<=Sylvester.precision);}},intersects:function(obj){if(typeof(obj.direction)=='undefined'&&typeof(obj.normal)=='undefined'){return null;}
return!this.isParallelTo(obj);},intersectionWith:function(obj){if(!this.intersects(obj)){return null;}
if(obj.direction){var A=obj.anchor.elements,D=obj.direction.elements,P=this.anchor.elements,N=this.normal.elements;var multiplier=(N[0]*(P[0]-A[0])+N[1]*(P[1]-A[1])+N[2]*(P[2]-A[2]))/(N[0]*D[0]+N[1]*D[1]+N[2]*D[2]);return Vector.create([A[0]+D[0]*multiplier,A[1]+D[1]*multiplier,A[2]+D[2]*multiplier]);}else if(obj.normal){var direction=this.normal.cross(obj.normal).toUnitVector();var N=this.normal.elements,A=this.anchor.elements,O=obj.normal.elements,B=obj.anchor.elements;var solver=Matrix.Zero(2,2),i=0;while(solver.isSingular()){i++;solver=Matrix.create([[N[i%3],N[(i+1)%3]],[O[i%3],O[(i+1)%3]]]);}
var inverse=solver.inverse().elements;var x=N[0]*A[0]+N[1]*A[1]+N[2]*A[2];var y=O[0]*B[0]+O[1]*B[1]+O[2]*B[2];var intersection=[inverse[0][0]*x+inverse[0][1]*y,inverse[1][0]*x+inverse[1][1]*y];var anchor=[];for(var j=1;j<=3;j++){anchor.push((i==j)?0:intersection[(j+(5-i)%3)%3]);}
return Line.create(anchor,direction);}},pointClosestTo:function(point){var P=point.elements||point;var A=this.anchor.elements,N=this.normal.elements;var dot=(A[0]-P[0])*N[0]+(A[1]-P[1])*N[1]+(A[2]-(P[2]||0))*N[2];return Vector.create([P[0]+N[0]*dot,P[1]+N[1]*dot,(P[2]||0)+N[2]*dot]);},rotate:function(t,line){var R=Matrix.Rotation(t,line.direction).elements;var C=line.pointClosestTo(this.anchor).elements;var A=this.anchor.elements,N=this.normal.elements;var C1=C[0],C2=C[1],C3=C[2],A1=A[0],A2=A[1],A3=A[2];var x=A1-C1,y=A2-C2,z=A3-C3;return Plane.create([C1+R[0][0]*x+R[0][1]*y+R[0][2]*z,C2+R[1][0]*x+R[1][1]*y+R[1][2]*z,C3+R[2][0]*x+R[2][1]*y+R[2][2]*z],[R[0][0]*N[0]+R[0][1]*N[1]+R[0][2]*N[2],R[1][0]*N[0]+R[1][1]*N[1]+R[1][2]*N[2],R[2][0]*N[0]+R[2][1]*N[1]+R[2][2]*N[2]]);},reflectionIn:function(obj){if(obj.normal){var A=this.anchor.elements,N=this.normal.elements;var A1=A[0],A2=A[1],A3=A[2],N1=N[0],N2=N[1],N3=N[2];var newA=this.anchor.reflectionIn(obj).elements;var AN1=A1+N1,AN2=A2+N2,AN3=A3+N3;var Q=obj.pointClosestTo([AN1,AN2,AN3]).elements;var newN=[Q[0]+(Q[0]-AN1)-newA[0],Q[1]+(Q[1]-AN2)-newA[1],Q[2]+(Q[2]-AN3)-newA[2]];return Plane.create(newA,newN);}else if(obj.direction){return this.rotate(Math.PI,obj);}else{var P=obj.elements||obj;return Plane.create(this.anchor.reflectionIn([P[0],P[1],(P[2]||0)]),this.normal);}},setVectors:function(anchor,v1,v2){anchor=Vector.create(anchor);anchor=anchor.to3D();if(anchor===null){return null;}
v1=Vector.create(v1);v1=v1.to3D();if(v1===null){return null;}
if(typeof(v2)=='undefined'){v2=null;}else{v2=Vector.create(v2);v2=v2.to3D();if(v2===null){return null;}}
var A1=anchor.elements[0],A2=anchor.elements[1],A3=anchor.elements[2];var v11=v1.elements[0],v12=v1.elements[1],v13=v1.elements[2];var normal,mod;if(v2!==null){var v21=v2.elements[0],v22=v2.elements[1],v23=v2.elements[2];normal=Vector.create([(v12-A2)*(v23-A3)-(v13-A3)*(v22-A2),(v13-A3)*(v21-A1)-(v11-A1)*(v23-A3),(v11-A1)*(v22-A2)-(v12-A2)*(v21-A1)]);mod=normal.modulus();if(mod===0){return null;}
normal=Vector.create([normal.elements[0]/mod,normal.elements[1]/mod,normal.elements[2]/mod]);}else{mod=Math.sqrt(v11*v11+v12*v12+v13*v13);if(mod===0){return null;}
normal=Vector.create([v1.elements[0]/mod,v1.elements[1]/mod,v1.elements[2]/mod]);}
this.anchor=anchor;this.normal=normal;return this;}};Plane.create=function(anchor,v1,v2){var P=new Plane();return P.setVectors(anchor,v1,v2);};Plane.XY=Plane.create(Vector.Zero(3),Vector.k);Plane.YZ=Plane.create(Vector.Zero(3),Vector.i);Plane.ZX=Plane.create(Vector.Zero(3),Vector.j);Plane.YX=Plane.XY;Plane.ZY=Plane.YZ;Plane.XZ=Plane.ZX;var $V=Vector.create;var $M=Matrix.create;var $L=Line.create;var $P=Plane.create;
//
// =========================== Trackball ===============================
//
// (c) Copyright 1993, 1994, Silicon Graphics, Inc.
// ALL RIGHTS RESERVED
// Permission to use, copy, modify, and distribute this software for
// any purpose and without fee is hereby granted, provided that the above
// copyright notice appear in all copies and that both the copyright notice
// and this permission notice appear in supporting documentation, and that
// the name of Silicon Graphics, Inc. not be used in advertising
// or publicity pertaining to distribution of the software without specific,
// written prior permission.
//
// THE MATERIAL EMBODIED ON THIS SOFTWARE IS PROVIDED TO YOU "AS-IS"
// AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED OR OTHERWISE,
// INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY OR
// FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL SILICON
// GRAPHICS, INC.  BE LIABLE TO YOU OR ANYONE ELSE FOR ANY DIRECT,
// SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY
// KIND, OR ANY DAMAGES WHATSOEVER, INCLUDING WITHOUT LIMITATION,
// LOSS OF PROFIT, LOSS OF USE, SAVINGS OR REVENUE, OR THE CLAIMS OF
// THIRD PARTIES, WHETHER OR NOT SILICON GRAPHICS, INC.  HAS BEEN
// ADVISED OF THE POSSIBILITY OF SUCH LOSS, HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE
// POSSESSION, USE OR PERFORMANCE OF THIS SOFTWARE.
//
function add_quats(q1,q2,dest){var count=0;var t1;var t2;var t3;var tf;t1=[0,0,0,0];t2=[0,0,0,0];t3=[0,0,0,0];tf=[0,0,0,0];vcopy(q1,t1);vscale(t1,q2[3]);vcopy(q2,t2);vscale(t2,q1[3]);vcross(q2,q1,t3);vadd(t1,t2,tf);vadd(t3,tf,tf);tf[3]=q1[3]*q2[3]-vdot(q1,q2);dest[0]=tf[0];dest[1]=tf[1];dest[2]=tf[2];dest[3]=tf[3];if(++count>97){count=0;normalize_quat(dest);}}
function axis_to_quat(a,phi,q){vnormal(a);vcopy(a,q);vscale(q,Math.sin(phi/2.0));q[3]=Math.cos(phi/2.0);}
function build_rotmatrix(m,q){m[0]=1.0-2.0*(q[1]*q[1]+q[2]*q[2]);m[1]=2.0*(q[0]*q[1]-q[2]*q[3]);m[2]=2.0*(q[2]*q[0]+q[1]*q[3]);m[3]=0.0;m[4]=2.0*(q[0]*q[1]+q[2]*q[3]);m[5]=1.0-2.0*(q[2]*q[2]+q[0]*q[0]);m[6]=2.0*(q[1]*q[2]-q[0]*q[3]);m[7]=0.0;m[8]=2.0*(q[2]*q[0]-q[1]*q[3]);m[9]=2.0*(q[1]*q[2]+q[0]*q[3]);m[10]=1.0-2.0*(q[1]*q[1]+q[0]*q[0]);m[11]=0.0;m[12]=0.0;m[13]=0.0;m[14]=0.0;m[15]=1.0;}
function normalize_quat(q){var i;var mag;mag=q[0]*q[0]+q[1]*q[1]+q[2]*q[2]+q[3]*q[3];for(i=0;i<4;i++){q[i]/=mag;}}
function tb_project_to_sphere(r,x,y){var d;var t;var z;d=Math.sqrt(x*x+y*y);if(d<r*0.70710678118654752440){z=Math.sqrt(r*r-d*d);}
else{t=(r/1.41421356237309504880);z=t*t/d;}
return z;}
function trackball(q,p1x,p1y,p2x,p2y){var a;var phi;var p1;var p2;var d;var t;a=[0,0,0];p1=[0,0,0];p2=[0,0,0];d=[0,0,0];if(p1x==p2x&&p1y==p2y){vzero(q);q[3]=1.0;return;}
vset(p1,p1x,p1y,tb_project_to_sphere(0.8,p1x,p1y));vset(p2,p2x,p2y,tb_project_to_sphere(0.8,p2x,p2y));vcross(p2,p1,a);vsub(p1,p2,d);t=vlength(d)/(1.6);if(t>1.0){t=1.0;}
if(t<-1.0){t=-1.0;}
phi=2.0*Math.asin(t);axis_to_quat(a,phi,q);}
function vadd(src1,src2,dst){dst[0]=src1[0]+src2[0];dst[1]=src1[1]+src2[1];dst[2]=src1[2]+src2[2];}
function vcopy(v1,v2){for(var i=0;i<3;i++){v2[i]=v1[i];}}
function vcross(v1,v2,cross){var temp=[0,0,0];temp[0]=v1[1]*v2[2]-v1[2]*v2[1];temp[1]=v1[2]*v2[0]-v1[0]*v2[2];temp[2]=v1[0]*v2[1]-v1[1]*v2[0];vcopy(temp,cross);}
function vdot(v1,v2){return v1[0]*v2[0]+v1[1]*v2[1]+v1[2]*v2[2];}
function vlength(v){return Math.sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);}
function vnormal(v){vscale(v,1.0/vlength(v));}
function vscale(v,div){v[0]*=div;v[1]*=div;v[2]*=div;}
function vset(v,x,y,z){v[0]=x;v[1]=y;v[2]=z;}
function vsub(src1,src2,dst){dst[0]=src1[0]-src2[0];dst[1]=src1[1]-src2[1];dst[2]=src1[2]-src2[2];}
function vzero(v){v[0]=0.0;v[1]=0.0;v[2]=0.0;}
//
// =========================== Queue ===============================
//
// Public Domain
//
function Queue(){var _1=[];var _2=0;this.getSize=function(){return _1.length-_2;};this.isEmpty=function(){return (_1.length==0);};this.enqueue=function(_3){_1.push(_3);};this.dequeue=function(){var _4=undefined;if(_1.length){_4=_1[_2];if(++_2*2>=_1.length){_1=_1.slice(_2);_2=0;}}return _4;};this.getOldestElement=function(){var _5=undefined;if(_1.length){_5=_1[_2];}return _5;};}
