      DOUBLE PRECISION FUNCTION SECOND()
     
********RETURNS THE ELAPSED CPU TIME, IN SECONDS.
********THIS ROUTINE IS OPERATING SYSTEM-DEPENDENT.
     
*     UNIX VERSION
      REAL ETIME
      REAL TARR(2)
      SECOND = ETIME(TARR)
      RETURN
      END
